### ISSUE TITLE
Not working for PWA capacitor based ionic

### ISSUE THREAD

**Issue by rajneshbiz** [pollfish/cordova-plugin-pollfish#10]
In PWA, I have followed the capacitor based ionic project guide.
But it seems it required cordova and only work for android and iOS build.

https://www.pollfish.com/docs/ionic

How Can I integrated it into my PWA.

**Comment by fotism23** [comment]
Currently we do not have support for ionic PWAs with Capacitor

We will keep you posted for any future updates
