### ISSUE TITLE
pollfishplugin is undefined

### ISSUE THREAD

**Issue by rajneshbiz** [pollfish/cordova-plugin-pollfish#9]
`pollfishplugin.init(releaseMode,rewardMode,api_key,pos,padding,request_uuid, offerwallMode); `

from where to import the `pollfishplugin` into `component` after 

`npm i https://github.com/pollfish/cordova-plugin-pollfish.git`

as `import { pollfishplugin } from 'com.pollfish.cordova_plugin'` this is not working
For ionic capacitor project .

**Comment by rajneshbiz** [comment]
Any update on this ?

**Comment by fotism23** [comment]
Hello @rajneshbiz and sorry for the late response

Capacitor based Ionic projects are facing the issue you've reported and we will provide a fix as soon as possible.

Thank you

**Comment by fotism23** [comment]
Hello @rajneshbiz 

We have released a new @ionic-native/pollfish TypeScript wrapper.

Docs are available [here](https://pollfish.com/docs/ionic)
